-- Converted from u472864586_odonto.sql (MariaDB 11.8) to PostgreSQL.
-- The source dump defines primary keys only; it contains no foreign-key constraints.

SET client_encoding = 'UTF8';

CREATE TABLE "acessos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "chave" varchar(50) NOT NULL,
  "grupo" INTEGER NOT NULL,
  "pagina" varchar(5) DEFAULT NULL
);

INSERT INTO "acessos" ("id", "nome", "chave", "grupo", "pagina") VALUES
(1, 'Home', 'home', 0, 'Sim'),
(2, 'Configurações', 'configuracoes', 0, 'Não'),
(3, 'Usuários', 'usuarios', 1, 'Sim'),
(4, 'Acessos', 'acessos', 2, 'Sim'),
(5, 'Grupos Acesso', 'grupo_acessos', 2, 'Sim'),
(8, 'Funcionários', 'funcionarios', 1, 'Sim'),
(9, 'Fornecedores', 'fornecedores', 1, 'Sim'),
(10, 'Formas de Pagamento', 'formas_pgto', 2, 'Sim'),
(11, 'Cargos', 'cargos', 2, 'Sim'),
(12, 'Frequências', 'frequencias', 2, 'Sim'),
(13, 'Contas à Receber', 'receber', 4, 'Sim'),
(14, 'Contas à Pagar', 'pagar', 4, 'Sim'),
(15, 'Clientes', 'clientes', 1, 'Sim'),
(16, 'Relatório Financeiro', 'rel_financeiro', 4, 'Não'),
(17, 'Relatório Sintético Despesas', 'rel_sintetico_despesas', 4, 'Não'),
(18, 'Relatório Sintético Receber', 'rel_sintetico_receber', 4, 'Não'),
(19, 'Relatório Balanço Anual', 'rel_balanco', 4, 'Não'),
(23, 'Caixas', 'caixas', 7, 'Sim'),
(24, 'Relatório De Caixas', 'rel_caixas', 7, 'Não'),
(25, 'Tarefas', 'tarefas', 0, 'Sim'),
(26, 'Lançar Tarefas', 'lancar_tarefas', 0, 'Não'),
(27, 'Relatório Inadimplentes', 'rel_inadimplementes', 4, 'Não'),
(36, 'Agenda', 'agendas', 0, 'Sim'),
(37, 'Procedimentos', 'procedimentos', 2, 'Sim'),
(38, 'Convênios', 'convenios', 2, 'Sim'),
(39, 'Agendamentos', 'agendamentos', 27, 'Sim'),
(40, 'Relatórios Agendamentos', 'rel_agendamentos', 27, 'Não'),
(41, 'Relatório de Procedimentos', 'rel_procedimentos', 27, 'Não'),
(44, 'Comissões', 'comissoes', 4, 'Sim'),
(45, 'Grupos de Anamnese', 'grupos_ana', 2, 'Sim'),
(46, 'Itens Anamnese', 'itens_ana', 2, 'Sim'),
(49, 'Recebimentos Convênio', 'recebimento_convenio', 4, 'Não'),
(50, 'Orçamentos', 'orcamentos', 0, 'Sim'),
(51, 'Tratamentos', 'tratamentos', 0, 'Sim'),
(52, 'Odontogramas', 'odontogramas', 0, 'Sim');

CREATE TABLE "agendamentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "funcionario" INTEGER NOT NULL,
  "paciente" INTEGER NOT NULL,
  "data" date NOT NULL,
  "hora" time NOT NULL,
  "obs" varchar(100) DEFAULT NULL,
  "data_lanc" date NOT NULL,
  "usuario" INTEGER NOT NULL,
  "status" varchar(30) NOT NULL,
  "servico" INTEGER NOT NULL,
  "hash" varchar(100) DEFAULT NULL,
  "pago" varchar(5) DEFAULT NULL,
  "tipo_pagamento" varchar(50) DEFAULT NULL,
  "valor" decimal(8,2) DEFAULT NULL,
  "convenio" INTEGER DEFAULT NULL,
  "retorno" varchar(5) DEFAULT NULL,
  "status_cor" varchar(50) DEFAULT NULL,
  "numero_convenio" varchar(100) DEFAULT NULL,
  "id_tratamento" INTEGER DEFAULT NULL
);

INSERT INTO "agendamentos" ("id", "funcionario", "paciente", "data", "hora", "obs", "data_lanc", "usuario", "status", "servico", "hash", "pago", "tipo_pagamento", "valor", "convenio", "retorno", "status_cor", "numero_convenio", "id_tratamento") VALUES
(64, 1, 94, '2025-04-24', '14:30:00', 'Cliente Plano Amil E90', '2025-04-15', 1, 'Agendado', 3, '', 'Não', NULL, NULL, 0, 'Não', NULL, NULL, NULL);

CREATE TABLE "anamnese" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente" INTEGER NOT NULL,
  "item" INTEGER NOT NULL,
  "descricao" varchar(255) DEFAULT NULL,
  "grupo" INTEGER NOT NULL
);

CREATE TABLE "anotacoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar(250) NOT NULL,
  "msg" text NOT NULL,
  "usuario" INTEGER NOT NULL,
  "data" date NOT NULL,
  "mostrar_home" varchar(5) NOT NULL,
  "privado" varchar(5) NOT NULL
);

CREATE TABLE "arquivos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) DEFAULT NULL,
  "descricao" varchar(100) DEFAULT NULL,
  "arquivo" varchar(100) DEFAULT NULL,
  "data_cad" date NOT NULL,
  "registro" varchar(50) DEFAULT NULL,
  "id_reg" INTEGER NOT NULL,
  "usuario" INTEGER NOT NULL
);

CREATE TABLE "caixas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "operador" INTEGER NOT NULL,
  "data_abertura" date NOT NULL,
  "data_fechamento" date DEFAULT NULL,
  "valor_abertura" decimal(8,2) NOT NULL,
  "valor_fechamento" decimal(8,2) DEFAULT NULL,
  "quebra" decimal(8,2) DEFAULT NULL,
  "usuario_abertura" INTEGER NOT NULL,
  "usuario_fechamento" INTEGER DEFAULT NULL,
  "obs" varchar(255) DEFAULT NULL,
  "sangrias" decimal(8,2) DEFAULT NULL
);

CREATE TABLE "cargos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL
);

INSERT INTO "cargos" ("id", "nome") VALUES
(1, 'Administrador'),
(5, 'Faxineiro'),
(51, 'Dentista'),
(52, 'Auxiliar Dentista'),
(53, 'Secretária'),
(54, '');

CREATE TABLE "clientes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "cpf" varchar(25) DEFAULT NULL,
  "telefone" varchar(20) DEFAULT NULL,
  "email" varchar(50) DEFAULT NULL,
  "endereco" varchar(100) DEFAULT NULL,
  "numero" varchar(10) DEFAULT NULL,
  "bairro" varchar(50) DEFAULT NULL,
  "cidade" varchar(50) DEFAULT NULL,
  "estado" varchar(50) DEFAULT NULL,
  "cep" varchar(20) DEFAULT NULL,
  "tipo_pessoa" varchar(15) DEFAULT NULL,
  "data_cad" date NOT NULL,
  "data_nasc" date DEFAULT NULL,
  "usuario" INTEGER DEFAULT NULL,
  "complemento" varchar(100) DEFAULT NULL,
  "tipo_sanguineo" varchar(30) DEFAULT NULL,
  "nome_responsavel" varchar(50) DEFAULT NULL,
  "cpf_responsavel" varchar(50) DEFAULT NULL,
  "convenio" INTEGER DEFAULT NULL,
  "sexo" varchar(25) DEFAULT NULL,
  "profissao" varchar(50) DEFAULT NULL,
  "estado_civil" varchar(25) DEFAULT NULL,
  "telefone2" varchar(20) DEFAULT NULL,
  "senha" varchar(100) DEFAULT NULL,
  "obs" varchar(500) DEFAULT NULL
);

INSERT INTO "clientes" ("id", "nome", "cpf", "telefone", "email", "endereco", "numero", "bairro", "cidade", "estado", "cep", "tipo_pessoa", "data_cad", "data_nasc", "usuario", "complemento", "tipo_sanguineo", "nome_responsavel", "cpf_responsavel", "convenio", "sexo", "profissao", "estado_civil", "telefone2", "senha", "obs") VALUES
(94, 'João Costa', '422.904.718-52', '11937039913', 'kefersonbuzatto90@gmail.com', 'Rua Augusto Bertolini', '114', 'Serpa', 'Caieiras', 'SP', '07714-010', 'Física', '2025-04-15', '2025-04-14', 1, 'casa 03', 'O+', 'Stomp Hair', '422.904.718-52', 3, 'M', 'Engenheiro de Software', 'Solteiro(a)', '(11) 93904-5927', NULL, 'Novo paciente');

CREATE TABLE "config" (
  "nome" varchar(50) DEFAULT NULL,
  "email" varchar(50) DEFAULT NULL,
  "telefone" varchar(20) DEFAULT NULL,
  "endereco" varchar(100) DEFAULT NULL,
  "instagram" varchar(100) DEFAULT NULL,
  "logo" varchar(100) DEFAULT NULL,
  "icone" varchar(100) DEFAULT NULL,
  "logo_rel" varchar(100) DEFAULT NULL,
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ativo" varchar(5) DEFAULT NULL,
  "multa_atraso" decimal(8,2) DEFAULT NULL,
  "juros_atraso" decimal(8,2) DEFAULT NULL,
  "marca_dagua" varchar(5) DEFAULT NULL,
  "assinatura_recibo" varchar(5) DEFAULT NULL,
  "impressao_automatica" varchar(5) DEFAULT NULL,
  "cnpj" varchar(25) DEFAULT NULL,
  "entrar_automatico" varchar(5) DEFAULT NULL,
  "mostrar_preloader" varchar(5) DEFAULT NULL,
  "ocultar_mobile" varchar(5) DEFAULT NULL,
  "api_whatsapp" varchar(25) DEFAULT NULL,
  "token_whatsapp" varchar(70) DEFAULT NULL,
  "instancia_whatsapp" varchar(70) DEFAULT NULL,
  "alterar_acessos" varchar(5) DEFAULT NULL,
  "dados_pagamento" varchar(100) DEFAULT NULL,
  "abertura_caixa" varchar(5) DEFAULT NULL,
  "horas_confirmacao" INTEGER DEFAULT NULL
);

INSERT INTO "config" ("nome", "email", "telefone", "endereco", "instagram", "logo", "icone", "logo_rel", "id", "ativo", "multa_atraso", "juros_atraso", "marca_dagua", "assinatura_recibo", "impressao_automatica", "cnpj", "entrar_automatico", "mostrar_preloader", "ocultar_mobile", "api_whatsapp", "token_whatsapp", "instancia_whatsapp", "alterar_acessos", "dados_pagamento", "abertura_caixa", "horas_confirmacao") VALUES
('Clínica Dental Health', 'contato@techsolutionspro.com.br', '(11) 93703-9913', 'Rua Augusto Bertolini, 114, Casa 03', 'techsolutionspro', 'logo.png', 'icone.png', 'logo.jpg', 1, 'Sim', 0.00, 0.00, 'Sim', 'Sim', 'Não', '58.169.516/0001-44', 'Sim', 'Sim', 'Não', 'menuia', 'b48795cd-ab50-4baa-9b0a-3bb4d65093a6', 'uGGRWxZ9yx06OmBcO8xAmn2bc1KQC0Sv1q3vJHGQQk1lK0cCSm', 'Sim', 'Pix Email: 58.169.516/0001-44', 'Não', 24);

CREATE TABLE "convenios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "comissao" INTEGER DEFAULT NULL,
  "telefone" varchar(20) DEFAULT NULL
);

INSERT INTO "convenios" ("id", "nome", "comissao", "telefone") VALUES
(1, 'Unimed', 50, '(00) 00000-0000'),
(3, 'Amil', 10, '(55) 55555-5555');

CREATE TABLE "dias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dia" varchar(25) NOT NULL,
  "funcionario" INTEGER NOT NULL,
  "inicio" time NOT NULL,
  "final" time NOT NULL,
  "inicio_almoco" time DEFAULT NULL,
  "final_almoco" time DEFAULT NULL,
  "data" date DEFAULT NULL
);

INSERT INTO "dias" ("id", "dia", "funcionario", "inicio", "final", "inicio_almoco", "final_almoco", "data") VALUES
(1, 'Segunda-Feira', 3, '08:00:00', '20:00:00', '12:00:00', '13:00:00', NULL),
(2, 'Terça-Feira', 3, '08:00:00', '20:00:00', '12:00:00', '13:00:00', NULL),
(3, 'Quarta-Feira', 3, '08:00:00', '20:00:00', '12:00:00', '13:00:00', NULL),
(4, 'Quinta-Feira', 3, '08:00:00', '20:00:00', '12:00:00', '13:00:00', NULL),
(5, 'Sexta-Feira', 3, '08:00:00', '21:00:00', '12:00:00', '13:00:00', NULL),
(6, 'Sábado', 3, '08:00:00', '20:00:00', '12:00:00', '13:00:00', NULL),
(8, 'Domingo', 3, '00:00:00', '00:00:00', '00:00:00', '00:00:00', '2024-11-09'),
(9, 'Segunda-Feira', 1, '09:00:00', '17:00:00', '00:00:00', '00:00:00', NULL),
(10, 'Terça-Feira', 1, '09:00:00', '17:00:00', '00:00:00', '00:00:00', NULL),
(11, 'Quarta-Feira', 1, '09:00:00', '17:00:00', '00:00:00', '00:00:00', NULL),
(12, 'Quinta-Feira', 1, '09:00:00', '17:00:00', '00:00:00', '00:00:00', NULL),
(13, 'Sexta-Feira', 1, '09:00:00', '20:00:00', '00:00:00', '00:00:00', NULL),
(14, 'Sábado', 1, '09:00:00', '17:00:00', '00:00:00', '00:00:00', NULL),
(16, 'Sábado', 1, '09:00:00', '17:00:00', '00:00:00', '00:00:00', NULL);

CREATE TABLE "formas_pgto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "taxa" INTEGER DEFAULT NULL
);

INSERT INTO "formas_pgto" ("id", "nome", "taxa") VALUES
(1, 'Dinheiro', 0),
(2, 'Pix', 0),
(3, 'Cartão de Crédito', 5),
(4, 'Cartão de Débito', 3);

CREATE TABLE "fornecedores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "telefone" varchar(50) NOT NULL,
  "email" varchar(50) DEFAULT NULL,
  "endereco" varchar(100) DEFAULT NULL,
  "pix" varchar(50) DEFAULT NULL,
  "data" date NOT NULL,
  "numero" varchar(10) DEFAULT NULL,
  "bairro" varchar(50) DEFAULT NULL,
  "cidade" varchar(50) DEFAULT NULL,
  "estado" varchar(50) DEFAULT NULL,
  "cep" varchar(20) DEFAULT NULL,
  "cnpj" varchar(20) DEFAULT NULL,
  "complemento" varchar(255) DEFAULT NULL,
  "tipo_chave" varchar(100) DEFAULT NULL,
  "usuario" INTEGER DEFAULT NULL
);

CREATE TABLE "frequencias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "frequencia" varchar(25) NOT NULL,
  "dias" INTEGER NOT NULL
);

INSERT INTO "frequencias" ("id", "frequencia", "dias") VALUES
(1, 'Nenhuma', 0),
(2, 'Diária', 1),
(3, 'Semanal', 7),
(4, 'Mensal', 30),
(5, 'Trimestral', 90),
(6, 'Semestral', 180),
(7, 'Anual', 365);

CREATE TABLE "func_proc" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "funcionario" INTEGER NOT NULL,
  "procedimento" INTEGER NOT NULL
);

INSERT INTO "func_proc" ("id", "funcionario", "procedimento") VALUES
(2, 3, 2),
(3, 3, 1),
(4, 3, 3),
(5, 1, 1),
(6, 1, 2),
(7, 1, 3);

CREATE TABLE "grupo_acessos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(25) NOT NULL
);

INSERT INTO "grupo_acessos" ("id", "nome") VALUES
(1, 'Pessoas'),
(2, 'Cadastros'),
(4, 'Financeiro'),
(7, 'Caixas'),
(27, 'Agendamentos');

CREATE TABLE "grupo_ana" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "descricao" varchar(2000) DEFAULT NULL
);

INSERT INTO "grupo_ana" ("id", "nome", "descricao") VALUES
(1, 'Hábitos Diários', ''),
(2, 'Condições do Paciente', ''),
(3, 'Doenças Cardiovasculares', ''),
(4, 'Histórico Familiar', ''),
(5, 'Grupo Teste', 'Descrição do Grupo'),
(13, 'Grupo teste 2', '');

CREATE TABLE "historico_paciente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente" INTEGER NOT NULL,
  "descricao" varchar(2000) NOT NULL,
  "data" date NOT NULL,
  "consulta" INTEGER NOT NULL,
  "funcionario" INTEGER NOT NULL,
  "nome_funcionario" varchar(50) DEFAULT NULL
);

CREATE TABLE "horarios_agd" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agendamento" INTEGER NOT NULL,
  "horario" time NOT NULL,
  "data" date NOT NULL,
  "funcionario" INTEGER NOT NULL,
  "id_tratamento" INTEGER DEFAULT NULL
);

INSERT INTO "horarios_agd" ("id", "agendamento", "horario", "data", "funcionario", "id_tratamento") VALUES
(2, 5, '18:40:00', '2024-10-29', 1, NULL),
(3, 6, '20:40:00', '2024-10-29', 1, NULL),
(4, 7, '16:00:00', '2024-10-29', 1, NULL),
(5, 8, '22:20:00', '2024-10-29', 1, NULL),
(6, 0, '09:15:00', '2024-10-29', 3, 3),
(7, 0, '10:15:00', '2024-10-30', 3, 3),
(8, 0, '08:15:00', '2024-11-04', 3, 3),
(9, 0, '09:15:00', '2024-11-05', 3, 3),
(10, 0, '10:15:00', '2024-11-06', 3, 3),
(11, 0, '18:15:00', '2024-11-04', 3, 6),
(12, 0, '18:15:00', '2024-11-05', 3, 6),
(13, 0, '18:15:00', '2024-11-11', 3, 6),
(14, 0, '18:15:00', '2024-11-12', 3, 6),
(15, 0, '18:15:00', '2024-11-18', 3, 6),
(16, 0, '18:15:00', '2024-11-19', 3, 6),
(17, 0, '18:15:00', '2024-11-25', 3, 6),
(18, 0, '18:15:00', '2024-11-26', 3, 6),
(19, 53, '14:30:00', '2024-11-14', 3, NULL),
(20, 54, '14:00:00', '2024-10-31', 1, NULL),
(21, 55, '20:40:00', '2024-10-31', 1, NULL),
(22, 56, '20:00:00', '2024-12-02', 3, NULL),
(23, 57, '20:15:00', '2024-12-02', 1, NULL),
(24, 58, '19:15:00', '2024-12-06', 1, NULL),
(25, 59, '10:45:00', '2024-12-19', 1, NULL),
(26, 60, '15:00:00', '2024-12-20', 1, NULL),
(27, 61, '12:45:00', '2024-12-19', 1, NULL),
(28, 62, '12:30:00', '2025-01-14', 1, NULL),
(29, 63, '14:00:00', '2025-02-21', 1, NULL);

CREATE TABLE "itens_ana" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grupo" INTEGER NOT NULL,
  "nome" varchar(255) NOT NULL,
  "descricao" varchar(1000) DEFAULT NULL
);

INSERT INTO "itens_ana" ("id", "grupo", "nome", "descricao") VALUES
(1, 1, 'Ingere bebida alcoolica?', ''),
(2, 1, 'Tabagismo?', ''),
(3, 1, 'Escova os Dentes todo dia?', ''),
(4, 1, 'Pratica atividade física?', ''),
(5, 2, 'Alergia a Medicamentos?', ''),
(6, 2, 'Fez cirurgia?', ''),
(7, 2, 'Gestações?', ''),
(8, 4, 'Câncer?', ''),
(9, 4, 'Diabetes?', ''),
(10, 4, 'Pressão Alta?', ''),
(11, 4, 'Outras Doenças?', ''),
(12, 3, 'Hipertensão arterial', ''),
(13, 3, 'Doença arterial periférica', ''),
(14, 3, 'Cardiopatia congênita', ''),
(15, 5, 'Teste 1', 'Descrição do Item'),
(16, 5, 'Teste 2', 'Descrição do Item 2'),
(17, 1, 'Problemas com Sono?', ''),
(22, 1, 'Fio Dental todos os dias?', ''),
(23, 13, 'fadsf dasfa', '');

CREATE TABLE "itens_odo" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "odontograma" INTEGER NOT NULL,
  "paciente" INTEGER NOT NULL,
  "data" date NOT NULL,
  "dente" INTEGER NOT NULL,
  "acao" varchar(50) DEFAULT NULL,
  "descricao" varchar(100) DEFAULT NULL,
  "obs" varchar(255) DEFAULT NULL,
  "funcionario" INTEGER NOT NULL,
  "deciduo" varchar(5) DEFAULT NULL
);

INSERT INTO "itens_odo" ("id", "odontograma", "paciente", "data", "dente", "acao", "descricao", "obs", "funcionario", "deciduo") VALUES
(7, 2, 4, '2024-10-30', 23, 'carie', 'fsdfdsf', 'fdsfdsf', 1, 'Não'),
(8, 2, 4, '2024-10-30', 25, 'carie', 'Canal a fazer aqui', 'fdsfds fdsafdsafa', 1, 'Não'),
(9, 2, 4, '2024-10-30', 45, 'carie', 'fdfds', 'fds', 1, 'Não'),
(10, 2, 4, '2024-10-30', 46, 'extrair', 'fdfds', 'fds', 1, 'Não'),
(11, 2, 4, '2024-10-30', 33, 'extrair', 'gfdg', 'gfdg', 1, 'Não'),
(12, 2, 4, '2024-10-30', 36, 'extraidos', 'gfdg', 'gfdg', 1, 'Não'),
(13, 2, 4, '2024-10-30', 37, 'tratados', 'gfdg', 'gfdg', 1, 'Não'),
(14, 2, 4, '2024-10-30', 43, 'extrair', 'ffdsfd', 'fdsfds', 1, 'Não'),
(15, 2, 4, '2024-10-30', 41, 'carie', 'fsdfdsf', 'fdsfs', 1, 'Não'),
(16, 2, 4, '2024-10-30', 52, 'extraidos', 'fdsfsd', 'fdsfds', 1, 'Sim'),
(17, 2, 4, '2024-10-30', 61, 'tratados', 'fdsfsd', 'fdsfds', 1, 'Sim'),
(18, 2, 4, '2024-10-30', 81, 'carie', 'fdsfsd', 'fdsfds', 1, 'Sim'),
(19, 2, 4, '2024-10-30', 72, 'carie', 'Canal', 'Após raio-x foi diagnosticado a necessidade de canal', 1, 'Sim'),
(20, 2, 4, '2024-10-30', 54, 'carie', 'Cárie na Face Oclusal e Cervical', 'Já solicitado Raio X para ver necessidade de Canal', 1, 'Sim'),
(21, 2, 4, '2024-10-30', 16, 'extraidos', 'Perda do Dente', '', 1, 'Não'),
(22, 3, 4, '2024-10-30', 17, 'extraidos', 'fdsfds', '', 1, 'Não'),
(23, 3, 5, '2024-10-30', 18, 'carie', 'fdsfds', 'fdsfsd', 1, 'Não'),
(24, 2, 4, '2024-10-30', 38, 'tratados', 'Finalizada a Restauração no dente, Face Mesial', 'Após 3 sessões finalizamos por completa as restaurações', 1, 'Não'),
(27, 2, 4, '2024-10-30', 18, 'tratados', 'Tratamento FInalizado', '', 1, 'Não'),
(28, 5, 4, '2024-10-31', 17, 'carie', 'Cárie Face Oclusal e Mesial', 'Solicitar raio x', 1, 'Não'),
(29, 5, 4, '2024-10-31', 16, 'extraidos', 'Extraído', '', 1, 'Não'),
(30, 5, 4, '2024-10-31', 13, 'extrair', 'Extração do dente', '', 1, 'Não'),
(31, 2, 4, '2024-10-31', 21, 'extraidos', 'Removido por maus cuidados', 'Teste', 1, 'Não'),
(32, 3, 5, '2024-10-31', 21, 'extrair', 'Extração de Dente', '', 1, 'Não'),
(35, 8, 80, '2024-10-31', 13, 'tratados', 'Retirado a Cárie', 'Dente já tratado', 1, 'Não'),
(36, 8, 80, '2024-10-31', 23, 'tratados', 'fdfdsf', 'fdfds', 1, 'Não'),
(38, 8, 80, '2024-10-31', 61, 'extraidos', 'fsdfds', 'fdsf', 1, 'Sim'),
(39, 8, 80, '2024-10-31', 82, 'extrair', 'fsdgfds', 'fdsfs', 1, 'Sim'),
(40, 2, 0, '2024-10-31', 14, 'carie', 'Tratar Canal', '', 1, 'Não'),
(42, 10, 86, '2024-10-31', 34, 'extraidos', 'fdfs', '', 1, 'Não'),
(44, 2, 0, '2024-10-31', 48, 'extrair', 'Extração com urgência', 'Dente bastante danificado', 1, 'Não'),
(46, 11, 4, '2024-10-31', 15, 'carie', 'Resturação na Fase Mesial', 'Necessita RaioX', 1, 'Não'),
(47, 11, 4, '2024-10-31', 17, 'extraidos', 'Dente extraido', '', 1, 'Não'),
(48, 11, 4, '2024-10-31', 21, 'tratados', 'Finalizado o Tratamento', 'Foi restaurado...', 1, 'Não'),
(49, 11, 4, '2024-10-31', 43, 'extrair', 'Extração fsdff ', 'fdafdsaf ', 1, 'Não'),
(51, 8, 80, '2024-10-31', 42, 'carie', 'Possível Cárie', 'Raiox Solicitado', 1, 'Não'),
(52, 8, 80, '2024-10-31', 33, 'extrair', 'fdsdsd', '', 1, 'Não'),
(53, 12, 4, '2024-12-05', 31, 'tratados', 'Remoção de tartaro', 'Paciente chegará em 20 mins', 1, 'Não');

CREATE TABLE "itens_orc" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "produto" INTEGER NOT NULL,
  "valor" decimal(8,2) NOT NULL,
  "quantidade" INTEGER NOT NULL,
  "total" decimal(8,2) NOT NULL,
  "id_orcamento" INTEGER NOT NULL,
  "funcionario" INTEGER NOT NULL,
  "descricao" varchar(255) DEFAULT NULL
);

INSERT INTO "itens_orc" ("id", "produto", "valor", "quantidade", "total", "id_orcamento", "funcionario", "descricao") VALUES
(10, 1, 190.00, 1, 190.00, 5, 1, 'fdsafd fd fa fa'),
(11, 3, 85.00, 1, 85.00, 5, 1, ''),
(12, 1, 190.00, 1, 190.00, 6, 1, 'vdaf dafasfadsf'),
(13, 2, 80.00, 1, 80.00, 6, 1, 'fdsafa fadf afdasf'),
(14, 1, 190.00, 1, 190.00, 7, 1, 'dfa dfdasfdjasfkdsakfdsa fkdsajfkasjfadfa fafds'),
(15, 3, 85.00, 1, 85.00, 7, 1, 'Remover carie em x dentes'),
(16, 2, 80.00, 1, 80.00, 7, 1, ''),
(17, 6, 50.00, 1, 50.00, 8, 1, ''),
(19, 8, 350.00, 1, 350.00, 8, 1, 'Proteses e Aparelho');

CREATE TABLE "odontograma" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente" INTEGER NOT NULL,
  "data" date NOT NULL,
  "descricao" varchar(100) DEFAULT NULL,
  "evolutivo" varchar(5) DEFAULT NULL,
  "funcionario" INTEGER DEFAULT NULL
);

INSERT INTO "odontograma" ("id", "paciente", "data", "descricao", "evolutivo", "funcionario") VALUES
(2, 4, '2024-10-30', 'Teste', 'Sim', 1),
(3, 5, '2024-10-30', 'Teste c22', 'Sim', 1),
(5, 4, '2024-10-31', 'Orçamento Prótese', 'Não', 1),
(8, 80, '2024-10-31', 'Teste cli 3', 'Sim', 1),
(10, 88, '2024-10-31', 'fdsfdsfdfdfd', 'Sim', 1),
(11, 4, '2024-10-31', 'Orçamento Prótese e Aparelho', 'Não', 1),
(12, 92, '2025-02-15', 'Extração', 'Sim', 1);

CREATE TABLE "orcamentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente" INTEGER NOT NULL,
  "data" date NOT NULL,
  "dias_validade" INTEGER NOT NULL,
  "valor" decimal(10,2) NOT NULL,
  "desconto" decimal(10,2) DEFAULT NULL,
  "tipo_desconto" varchar(25) DEFAULT NULL,
  "subtotal" decimal(10,2) NOT NULL,
  "obs" varchar(255) DEFAULT NULL,
  "status" varchar(25) DEFAULT NULL,
  "usuario" INTEGER NOT NULL,
  "forma_pgto" INTEGER DEFAULT NULL,
  "hora" time DEFAULT NULL,
  "tipo" varchar(25) DEFAULT NULL,
  "data_aprovacao" date DEFAULT NULL,
  "odontograma" INTEGER DEFAULT NULL
);

CREATE TABLE "pagar" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar(100) DEFAULT NULL,
  "fornecedor" INTEGER NOT NULL,
  "funcionario" INTEGER NOT NULL,
  "valor" decimal(8,2) NOT NULL,
  "vencimento" date NOT NULL,
  "data_pgto" date DEFAULT NULL,
  "data_lanc" date NOT NULL,
  "forma_pgto" INTEGER NOT NULL,
  "frequencia" INTEGER NOT NULL,
  "obs" varchar(100) DEFAULT NULL,
  "arquivo" varchar(100) DEFAULT NULL,
  "referencia" varchar(30) DEFAULT NULL,
  "id_ref" INTEGER DEFAULT NULL,
  "multa" decimal(8,2) DEFAULT NULL,
  "juros" decimal(8,2) DEFAULT NULL,
  "desconto" decimal(8,2) DEFAULT NULL,
  "taxa" decimal(8,2) DEFAULT NULL,
  "subtotal" decimal(8,2) DEFAULT NULL,
  "usuario_lanc" INTEGER NOT NULL,
  "usuario_pgto" INTEGER NOT NULL,
  "pago" varchar(5) DEFAULT NULL,
  "residuo" varchar(5) DEFAULT NULL,
  "hora" time DEFAULT NULL,
  "hash" varchar(100) DEFAULT NULL,
  "caixa" INTEGER DEFAULT NULL,
  "quant_recorrencia" INTEGER DEFAULT NULL,
  "recorrencia_inf" varchar(5) DEFAULT NULL,
  "id_recorrencia" INTEGER DEFAULT NULL
);

INSERT INTO "pagar" ("id", "descricao", "fornecedor", "funcionario", "valor", "vencimento", "data_pgto", "data_lanc", "forma_pgto", "frequencia", "obs", "arquivo", "referencia", "id_ref", "multa", "juros", "desconto", "taxa", "subtotal", "usuario_lanc", "usuario_pgto", "pago", "residuo", "hora", "hash", "caixa", "quant_recorrencia", "recorrencia_inf", "id_recorrencia") VALUES
(1, 'Comissão - Limpeza', 0, 1, 95.00, '2024-10-29', '2024-10-29', '2024-10-29', 0, 0, NULL, 'sem-foto.png', 'Comissão', 1, NULL, NULL, NULL, NULL, 95.00, 1, 1, 'Sim', NULL, '11:49:20', NULL, 2, NULL, NULL, NULL),
(2, 'Comissão - Manutenção Aparelho', 0, 1, 40.00, '2024-10-29', '2024-10-29', '2024-10-29', 0, 0, NULL, 'sem-foto.png', 'Comissão', 2, NULL, NULL, NULL, NULL, 40.00, 1, 1, 'Sim', NULL, '11:49:20', NULL, 2, NULL, NULL, NULL),
(3, 'Comissão - Manutenção Aparelho', 0, 3, 8.00, '2024-10-29', '2024-10-29', '2024-10-29', 2, 0, NULL, 'sem-foto.png', 'Comissão', 2, NULL, NULL, NULL, NULL, 8.00, 1, 1, 'Sim', NULL, '20:43:24', NULL, 2, NULL, NULL, NULL);

CREATE TABLE "procedimentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "valor" decimal(8,2) NOT NULL,
  "tempo" INTEGER NOT NULL,
  "ativo" varchar(5) NOT NULL,
  "exame" varchar(5) DEFAULT NULL,
  "convenio" varchar(5) DEFAULT NULL,
  "preparo" varchar(255) DEFAULT NULL
);

INSERT INTO "procedimentos" ("id", "nome", "valor", "tempo", "ativo", "exame", "convenio", "preparo") VALUES
(1, 'Limpeza', 190.00, 30, 'Sim', '', 'Sim', ''),
(2, 'Manutenção Aparelho', 80.00, 20, 'Sim', '', 'Sim', ''),
(3, 'Remoção de Cárie', 85.00, 15, 'Sim', '', 'Sim', ''),
(6, 'Diagnóse e Vistoria', 50.00, 15, 'Sim', '', 'Não', ''),
(7, 'Radiologia', 70.00, 15, 'Sim', '', 'Sim', ''),
(8, 'Prótese', 350.00, 30, 'Sim', '', 'Não', ''),
(9, 'Facetas', 200.00, 60, 'Sim', '', 'Não', '');

CREATE TABLE "raiox" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente" INTEGER DEFAULT NULL,
  "dentista" INTEGER DEFAULT NULL,
  "descricao" varchar(1000) DEFAULT NULL,
  "data" date DEFAULT NULL,
  "clinica" varchar(100) DEFAULT NULL,
  "procedimento" varchar(100) DEFAULT NULL
);

INSERT INTO "raiox" ("id", "paciente", "dentista", "descricao", "data", "clinica", "procedimento") VALUES
(6, 5, 1, 'Pedido raio x para remoção de cárie, favor enviar em CD', '2024-10-29', 'Sim', 'Remoção de Cárie'),
(7, 5, 1, 'fdsfadfdsafdsafasf fa df afa ', '2024-10-29', 'Sim', 'Manutenção Aparelho'),
(9, 4, 1, 'fadsfas fadsfa fsads fdsafasdfa sf', '2024-10-29', 'Não', 'fdsfsdfdsafa fd af'),
(10, 4, 1, 'fad fasfd adfsda fdasfdsa fa fdfad fsafa', '2024-10-29', 'Sim', 'Limpeza');

CREATE TABLE "receber" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar(100) DEFAULT NULL,
  "cliente" INTEGER NOT NULL,
  "valor" decimal(8,2) NOT NULL,
  "vencimento" date NOT NULL,
  "data_pgto" date DEFAULT NULL,
  "data_lanc" date NOT NULL,
  "forma_pgto" INTEGER NOT NULL,
  "frequencia" INTEGER NOT NULL,
  "obs" varchar(100) DEFAULT NULL,
  "arquivo" varchar(100) DEFAULT NULL,
  "referencia" varchar(30) DEFAULT NULL,
  "id_ref" INTEGER DEFAULT NULL,
  "multa" decimal(8,2) DEFAULT NULL,
  "juros" decimal(8,2) DEFAULT NULL,
  "desconto" decimal(8,2) DEFAULT NULL,
  "taxa" decimal(8,2) DEFAULT NULL,
  "subtotal" decimal(8,2) DEFAULT NULL,
  "usuario_lanc" INTEGER NOT NULL,
  "usuario_pgto" INTEGER NOT NULL,
  "pago" varchar(5) DEFAULT NULL,
  "residuo" varchar(5) DEFAULT NULL,
  "hora" time DEFAULT NULL,
  "hash" varchar(100) DEFAULT NULL,
  "caixa" INTEGER DEFAULT NULL,
  "tipo_chave" varchar(50) DEFAULT NULL,
  "acessar_painel" varchar(5) NOT NULL,
  "quant_recorrencia" INTEGER DEFAULT NULL,
  "id_recorrencia" INTEGER DEFAULT NULL,
  "convenio" INTEGER DEFAULT NULL
);

CREATE TABLE "sangrias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario" INTEGER NOT NULL,
  "valor" decimal(8,2) NOT NULL,
  "data" date NOT NULL,
  "hora" time NOT NULL,
  "caixa" INTEGER NOT NULL
);

CREATE TABLE "tarefas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario" INTEGER NOT NULL,
  "usuario_lanc" INTEGER NOT NULL,
  "data" date NOT NULL,
  "hora" time NOT NULL,
  "hora_mensagem" time DEFAULT NULL,
  "descricao" varchar(255) DEFAULT NULL,
  "status" varchar(20) DEFAULT NULL,
  "hash" varchar(100) DEFAULT NULL,
  "prioridade" varchar(25) DEFAULT NULL
);

CREATE TABLE "tratamentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paciente" INTEGER NOT NULL,
  "procedimento" INTEGER NOT NULL,
  "profissional" INTEGER NOT NULL,
  "data_inicial" date NOT NULL,
  "data_final" date NOT NULL,
  "frequencia" INTEGER NOT NULL,
  "hora1" time DEFAULT NULL,
  "hora2" time DEFAULT NULL,
  "hora3" time DEFAULT NULL,
  "hora4" time DEFAULT NULL,
  "hora5" time DEFAULT NULL,
  "hora6" time DEFAULT NULL,
  "quitado" varchar(5) DEFAULT NULL,
  "data" date DEFAULT NULL
);

INSERT INTO "tratamentos" ("id", "paciente", "procedimento", "profissional", "data_inicial", "data_final", "frequencia", "hora1", "hora2", "hora3", "hora4", "hora5", "hora6", "quitado", "data") VALUES
(3, 4, 2, 3, '2024-10-29', '2024-11-07', 3, '08:00:00', '09:00:00', '10:00:00', '00:00:00', '00:00:00', '00:00:00', 'Sim', '2024-10-29'),
(5, 5, 3, 3, '2024-10-29', '2024-11-06', 2, '16:00:00', '16:00:00', '00:00:00', '00:00:00', '00:00:00', '00:00:00', 'Sim', '2024-10-29'),
(6, 5, 2, 3, '2024-11-01', '2024-12-01', 2, '18:00:00', '18:00:00', '00:00:00', '00:00:00', '00:00:00', '00:00:00', 'Sim', '2024-10-29');

CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(50) NOT NULL,
  "email" varchar(50) NOT NULL,
  "senha" varchar(50) DEFAULT NULL,
  "senha_crip" varchar(130) NOT NULL,
  "nivel" varchar(25) NOT NULL,
  "ativo" varchar(5) NOT NULL,
  "telefone" varchar(20) DEFAULT NULL,
  "endereco" varchar(150) DEFAULT NULL,
  "foto" varchar(100) DEFAULT NULL,
  "data" date NOT NULL,
  "comissao" INTEGER DEFAULT NULL,
  "id_ref" INTEGER NOT NULL,
  "pix" varchar(100) DEFAULT NULL,
  "token" varchar(150) DEFAULT NULL,
  "data_nasc" date DEFAULT NULL,
  "numero" varchar(10) DEFAULT NULL,
  "bairro" varchar(50) DEFAULT NULL,
  "cidade" varchar(50) DEFAULT NULL,
  "estado" varchar(50) DEFAULT NULL,
  "cep" varchar(20) DEFAULT NULL,
  "acessar_painel" varchar(5) DEFAULT NULL,
  "cpf" varchar(20) DEFAULT NULL,
  "mostrar_registros" varchar(5) DEFAULT NULL,
  "complemento" varchar(100) DEFAULT NULL,
  "tipo_chave" varchar(100) DEFAULT NULL,
  "atendimento" varchar(5) DEFAULT NULL,
  "intervalo" INTEGER DEFAULT NULL,
  "cro" varchar(20) DEFAULT NULL
);

INSERT INTO "usuarios" ("id", "nome", "email", "senha", "senha_crip", "nivel", "ativo", "telefone", "endereco", "foto", "data", "comissao", "id_ref", "pix", "token", "data_nasc", "numero", "bairro", "cidade", "estado", "cep", "acessar_painel", "cpf", "mostrar_registros", "complemento", "tipo_chave", "atendimento", "intervalo", "cro") VALUES
(1, 'Clínica Dental Health', 'contato@techsolutionspro.com.br', '', '$2y$10$N2tYCq3LEY6H2e3JuLOJP.p5ltt9.IW37fxA5AcSvxgadHL51Eyku', 'Administrador', 'Sim', '(11) 93703-9913', 'Rua Augusto Bertolini', '09-04-2025-21-43-29-avatar-admin.png', '2024-10-27', 50, 0, '0000000000', '', '1990-11-07', '114', 'Serpa', 'Caieiras', 'SP', '07714-010', '', NULL, 'Sim', '', 'CPF', 'Sim', 15, 'MG 4122222'),
(4, 'Dentista', 'testegratis@techsolutionspro.com.br', '', '$2y$10$igJz3gdyb.6PIxkmvoahEeZUJWMzFh6YZU66CUbT5Z53zupugttnC', 'Dentista', 'Sim', '(11) 95688-1043', '', '17-12-2025-09-36-43-logotipo-tspro-fotor-20251102211655-(1).png', '2024-12-05', NULL, 0, '', NULL, '2024-12-04', '100', '', '', '', '07700-000', 'Sim', '422.904.718-52', 'Sim', 'casa 03', '', NULL, NULL, NULL);

CREATE TABLE "usuarios_permissoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario" INTEGER NOT NULL,
  "permissao" INTEGER NOT NULL
);

INSERT INTO "usuarios_permissoes" ("id", "usuario", "permissao") VALUES
(45, 2, 1),
(46, 2, 2),
(47, 2, 3),
(48, 2, 4),
(49, 2, 5),
(50, 2, 8),
(51, 2, 9),
(52, 2, 10),
(53, 2, 11),
(54, 2, 12),
(55, 2, 13),
(56, 2, 14),
(57, 2, 15),
(58, 2, 16),
(59, 2, 17),
(60, 2, 18),
(61, 2, 19),
(62, 2, 23),
(63, 2, 24),
(64, 2, 25),
(65, 2, 26),
(66, 2, 27),
(67, 2, 36),
(68, 2, 37),
(69, 2, 38),
(70, 2, 39),
(71, 2, 40),
(72, 2, 41),
(73, 3, 1),
(74, 3, 2),
(75, 3, 3),
(76, 3, 4),
(77, 3, 5),
(78, 3, 8),
(79, 3, 9),
(80, 3, 10),
(81, 3, 11),
(82, 3, 12),
(83, 3, 13),
(84, 3, 14),
(85, 3, 15),
(86, 3, 16),
(87, 3, 17),
(88, 3, 18),
(89, 3, 19),
(90, 3, 23),
(91, 3, 24),
(92, 3, 25),
(93, 3, 26),
(94, 3, 27),
(95, 3, 36),
(96, 3, 37),
(97, 3, 38),
(98, 3, 39),
(99, 3, 40),
(100, 3, 41),
(101, 4, 1),
(104, 4, 4),
(105, 4, 5),
(106, 4, 8),
(107, 4, 9),
(108, 4, 10),
(109, 4, 11),
(110, 4, 12),
(111, 4, 13),
(112, 4, 14),
(113, 4, 15),
(114, 4, 16),
(115, 4, 17),
(116, 4, 18),
(117, 4, 19),
(118, 4, 23),
(119, 4, 24),
(120, 4, 25),
(121, 4, 26),
(122, 4, 27),
(123, 4, 36),
(124, 4, 37),
(125, 4, 38),
(126, 4, 39),
(127, 4, 40),
(128, 4, 41),
(129, 4, 44),
(130, 4, 45),
(131, 4, 46),
(132, 4, 49),
(133, 4, 50),
(134, 4, 51),
(135, 4, 52);

-- Preserve the next AUTO_INCREMENT values declared by the source dump.
ALTER TABLE "acessos" ALTER COLUMN "id" RESTART WITH 53;
ALTER TABLE "agendamentos" ALTER COLUMN "id" RESTART WITH 65;
ALTER TABLE "anamnese" ALTER COLUMN "id" RESTART WITH 19;
ALTER TABLE "anotacoes" ALTER COLUMN "id" RESTART WITH 3;
ALTER TABLE "arquivos" ALTER COLUMN "id" RESTART WITH 37;
ALTER TABLE "caixas" ALTER COLUMN "id" RESTART WITH 4;
ALTER TABLE "cargos" ALTER COLUMN "id" RESTART WITH 55;
ALTER TABLE "clientes" ALTER COLUMN "id" RESTART WITH 95;
ALTER TABLE "config" ALTER COLUMN "id" RESTART WITH 2;
ALTER TABLE "convenios" ALTER COLUMN "id" RESTART WITH 4;
ALTER TABLE "dias" ALTER COLUMN "id" RESTART WITH 17;
ALTER TABLE "formas_pgto" ALTER COLUMN "id" RESTART WITH 26;
ALTER TABLE "fornecedores" ALTER COLUMN "id" RESTART WITH 11;
ALTER TABLE "frequencias" ALTER COLUMN "id" RESTART WITH 21;
ALTER TABLE "func_proc" ALTER COLUMN "id" RESTART WITH 8;
ALTER TABLE "grupo_acessos" ALTER COLUMN "id" RESTART WITH 28;
ALTER TABLE "grupo_ana" ALTER COLUMN "id" RESTART WITH 14;
ALTER TABLE "historico_paciente" ALTER COLUMN "id" RESTART WITH 9;
ALTER TABLE "horarios_agd" ALTER COLUMN "id" RESTART WITH 30;
ALTER TABLE "itens_ana" ALTER COLUMN "id" RESTART WITH 24;
ALTER TABLE "itens_odo" ALTER COLUMN "id" RESTART WITH 54;
ALTER TABLE "itens_orc" ALTER COLUMN "id" RESTART WITH 20;
ALTER TABLE "odontograma" ALTER COLUMN "id" RESTART WITH 13;
ALTER TABLE "orcamentos" ALTER COLUMN "id" RESTART WITH 9;
ALTER TABLE "pagar" ALTER COLUMN "id" RESTART WITH 7;
ALTER TABLE "procedimentos" ALTER COLUMN "id" RESTART WITH 10;
ALTER TABLE "raiox" ALTER COLUMN "id" RESTART WITH 11;
ALTER TABLE "receber" ALTER COLUMN "id" RESTART WITH 11;
ALTER TABLE "sangrias" ALTER COLUMN "id" RESTART WITH 12;
ALTER TABLE "tarefas" ALTER COLUMN "id" RESTART WITH 9;
ALTER TABLE "tratamentos" ALTER COLUMN "id" RESTART WITH 7;
ALTER TABLE "usuarios" ALTER COLUMN "id" RESTART WITH 6;
ALTER TABLE "usuarios_permissoes" ALTER COLUMN "id" RESTART WITH 136;

